### ISSUE TITLE
Book Displays w/ Blue Characters

### ISSUE THREAD

**Issue by bbuyukcelen** [RebusFoundation/reader-frontend#85] opened 2019-06-28 13:46 UTC
Book displays mostly blue, some in black characters. It displays properly in ibooks.

Sending book via slack
![Screen Shot 2019-06-28 at 09 33 56](https://user-images.githubusercontent.com/42753145/60346651-93c15100-9989-11e9-8ec0-4e13e8df933f.png)
![Screen Shot 2019-06-28 at 09 34 07](https://user-images.githubusercontent.com/42753145/60346652-93c15100-9989-11e9-96fe-69924dfedc45.png)

**Comment by baldurbjarnason** [comment] 2019-06-28 15:24
Turns out that this, #82 and #78 are all related bugs. The issue is basically that Ink sometimes uses an HTML parser for XHTML files in the last step of processing before rendering which messes up the display of the file.

I have fixed this locally so these bugs _should_ be fixed once I deploy the current version.

**Closed** 2019-07-11 16:26 UTC
